version: '3'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./packages/frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
    restart: always